on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          package-name: release-please-action
          extra-files: core/lib/data/def.go

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-go@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          go-version: "^1.21"

      - name: Upload URL
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo 'Upload to ${{ steps.release.outputs.upload_url }}'

      - name: Create archive and upload assets
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cd core || exit 1
          ls -lah
          bash ./emp3r0r --release || exit 2
          mv emp3r0r.tar.xz emp3r0r-v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}.tar.xz || exit 3
          ls -lah
          bash ./upload.sh github_api_token=${{ secrets.GITHUB_TOKEN }} owner=jm33-m0 repo=emp3r0r tag=v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }} filename=./emp3r0r-v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}.tar.xz
